### PR TITLE
switch component to toggle modes

### PR DESCRIPTION
**Pull request by rhygg**

### CODE REVIEW

**Review by twlite — CHANGES_REQUESTED** [review]
BG color of the switch is not okay in dark mode
image

**Comment by rhygg** [comment]
> BG color of the switch is not okay in dark mode
> image

Would love the hex code.

**Comment by rhygg** [comment]
@DevAndromeda changed the switch color 👍🏻

**Comment by twlite** [comment]
maybe there should be an outline in the dark mode?
image

**Comment by rhygg** [comment]
> maybe there should be an outline in the dark mode?
> image

yeah, sure! 👍🏻

**Comment by twlite** [comment]
I think width 55 looks better than 70 🤔🤔

**Comment by rhygg** [comment]
really? Alright!

**Comment by rhygg** [comment]
@DevAndromeda so basically the `<Switch />` component doesn't have a style prop so can't really add an outline. If you have another idea let me know! 
Also, should I push the search popup or not?

**Comment by twlite** [comment]
> should I push the search popup or not?

maybe in separate PR

**Comment by rhygg** [comment]
@DevAndromeda is everything alright here? Merge pr?

**Pull request merged**
